site_name: Guidance Docs
repo_url: https://github.com/roastedroot/wasm-java-agents-blueprint
repo_name: wasm-java-agents-blueprint

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Customization Guide: customization.md

theme:
  name: material
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: images/Blueprint-logo-white.png
  favicon: images/Blueprint-logo-black-favicon.png
  extra_css:
    - assets/custom.css
  features:
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
